// Automatically generated by ./configure 
#pragma once
#define ARCH "x86_64"
#define CPU "generic"
#define WITHOUT_OPTIMIZATION 0
#define ENABLE_DEVEL 0
#define ENABLE_VALGRIND 0
#define ENABLE_REFCNT_DEBUG 0
#define ENABLE_SHAREDPTR_DEBUG 0
#define ENABLE_LZ4 1
#define ENABLE_SSL 1
#define ENABLE_SASL 1
#define MKL_APP_NAME "librdkafka"
#define MKL_APP_DESC_ONELINE "The Apache Kafka C/C++ library"
// gcc
#define WITH_GCC 1
// gxx
#define WITH_GXX 1
// PIC
#define HAVE_PIC 1
// parseversion
#define RDKAFKA_VERSION_STR "0.9.4"
// parseversion
#define MKL_APP_VERSION "0.9.4"
// zlib
#define WITH_ZLIB 1
// WITH_SNAPPY
#define WITH_SNAPPY 1
// WITH_SOCKEM
#define WITH_SOCKEM 1
// libsasl2
#define WITH_SASL 0
// regex
#define HAVE_REGEX 1
// strndup
#define HAVE_STRNDUP 1
